name: huefinder
description: "A color matching game built with Flutter that teaches RGB color theory through engaging gameplay."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.2

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/ios_icon.png"
  image_path_android: "assets/android_icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/android_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#121212"

  android_flut12:
    color: "#121212"